---

# Jellyfin repo (Debian/Ubuntu)

- name: Ensure curl and gnupg are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - gnupg

- name: Add Jellyfin repo signing key
  ansible.builtin.apt_key:
    url: "https://repo.jellyfin.org/jellyfin_team.gpg.key"
    state: present

- name: Add Jellyfin repo
  ansible.builtin.apt_repository:
    repo: "deb https://repo.jellyfin.org/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] | lower }} main"
    state: present
    update_cache: true
